import React from "react";
import User from "./UserDTO";
import DetailDTO from "./alert.detil.dto";
import Role from "./role.type";
import { CompanyDTO } from "../interfaces/CompanyDTO.ts";
interface AppContextType {
    depositList: any[] | undefined;
    setDepositList: React.Dispatch<React.SetStateAction<any[] | undefined>>;
    auth: User | undefined;
    change: boolean;
    setAuth: React.Dispatch<React.SetStateAction<User | undefined>>;
    setOpen: React.Dispatch<React.SetStateAction<boolean>>;
    setChange: React.Dispatch<React.SetStateAction<boolean>>;
    setDetail: React.Dispatch<React.SetStateAction<DetailDTO | undefined>>;
    selectedOption: Role;
    setSelectedOption: React.Dispatch<React.SetStateAction<Role>>;
    dialogOpen: boolean;
    setDialogOpen: React.Dispatch<React.SetStateAction<boolean>>;
    defaultNavActive: boolean;
    setDefaultNavActive: React.Dispatch<React.SetStateAction<boolean>>;
    dialogType:string;
    setDialogType:React.Dispatch<React.SetStateAction<string>>;
    selectedCompanyId:number|null;
    setSelectedCompanyId:React.Dispatch<React.SetStateAction<number|null>>;
    company:CompanyDTO|undefined;
    setCompany:React.Dispatch<React.SetStateAction<CompanyDTO|undefined>>;
    openNavbarDialog:boolean;
    setOpenNavbarDialog:React.Dispatch<React.SetStateAction<boolean>>;
}
export default AppContextType;